### ISSUE TITLE
Install Error : ubuntu 20.04.6 ARM64 [MAC M1 chip - Parallels 19]

### ISSUE THREAD

**Issue by j30231** [tpm2-software/tpm2-pytss#573] opened 2024-04-24 06:12 UTC
conducted the installation in the following environment to use TPM2-PYTSS.

CPU : Apple MAC m1 chip
VM : Parallels 19 on MAC
VM-OS : Ubuntu 20.04.6 ARM64 (with vTPM Chip )
*Parallels offers TPM chips in virtual environments.

However, the error continues to occur. The error message is as follows.

----------
jj@tpm:~$ pip install tpm2-pytss

<pre><code>
Collecting tpm2-pytss
  Using cached tpm2-pytss-2.2.1.tar.gz (208 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpgz3touat prepare_metadata_for_build_wheel /tmp/tmpr2rygswc
         cwd: /tmp/pip-install-j3owqq3b/tpm2-pytss
    Complete output (50 lines):
    /tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of None already set
      warnings.warn(f"version of {dist_name} already set")
    adding path: /tmp/pip-install-j3owqq3b/tpm2-pytss/scripts
    Traceback (most recent call last):
      File "/tmp/tmpgz3touat", line 280, in <module>
        main()
      File "/tmp/tmpgz3touat", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpgz3touat", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
        exec(code, locals())
      File "<string>", line 285, in <module>
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 146, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 307, in __init__
        _Distribution.__init__(self, dist_attrs)
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 284, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 658, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-ny2qq4o3/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 678, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "scripts/libtss2_build.py", line 69, in <module>
        ffibuilder.cdef(open("libesys.h").read())
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/cparser.py", line 389, in parse
        self._internal_parse(csource)
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/cparser.py", line 396, in _internal_parse
        self._process_macros(macros)
      File "/tmp/pip-build-env-ny2qq4o3/normal/lib/python3.8/site-packages/cffi/cparser.py", line 479, in _process_macros
        raise CDefError(
    cffi.CDefError: only supports one of the following syntax:
      #define TPM2_HR_PCR ...     (literally dot-dot-dot)
      #define TPM2_HR_PCR NUMBER  (with NUMBER an integer constant, decimal/hex/octal)
    got:
      #define TPM2_HR_PCR ...<< TPM2_HR_SHIFT)
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpgz3touat prepare_metadata_for_build_wheel /tmp/tmpr2rygswc Check the logs for full command output.
</code></pre>

**Comment by j30231** [comment] 2024-04-24 06:15
For your information, TPM2-TSS and TPM2-TOOLS are well installed, and I've also checked if they work well.

--------

jj@tpm:~$ sudo tpm2_pcrread

<pre><code>
sha1:
  0 : 0x5CA4EF8FE0F5F4DFC6DA5874B9A350EE38D86262
  1 : 0x1FDDE30A84CD40CDDFDBCA63DDC9703641F7D0AA
  2 : 0xB2A83B0EBF2F8374299A5B2BDFC31EA955AD7236
  3 : 0xB2A83B0EBF2F8374299A5B2BDFC31EA955AD7236
  4 : 0x65CF5E0DA1513025532620CBAFD1CBB0DAE7F1E9
  5 : 0x3D4C2CDD333660F1B4BC510125E8E92DA513817E
  6 : 0xB2A83B0EBF2F8374299A5B2BDFC31EA955AD7236
  7 : 0xE9A8F1813842EE844B167F3DE2A8565770B4653A
  8 : 0x0000000000000000000000000000000000000000
  9 : 0x0000000000000000000000000000000000000000
  10: 0x385855C710E3DEEF40B4BCA59A250C24DF36339A
  11: 0x0000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000
  14: 0xA482A15E112717D6A915B989A0EA6140A507E3E6
  15: 0x0000000000000000000000000000000000000000
  16: 0x0000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000
sha256:
  0 : 0x813F8C8C4BB45F1550A7B62E215B978F05E60FEB1F9B5F32A86776A4DD692318
  1 : 0x195B0BB2E08E399EE99334F3B03FB645007E4E9274B9ECE06562C545BBE9ABE5
  2 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
  3 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
  4 : 0x42D762D28305AA49062ECF6CCC0790701E263AFB14037FA4116A604105CBC11E
  5 : 0xC6E71675D4FDD643CC63EC2F1A46015BBA73D7A50B83CCF59BB7C8B2E6973F43
  6 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
  7 : 0x59D9D1BAF04ABD31FC7428EE4E3E2F724979A87453BFEE6AD2826D03025CBAD0
  8 : 0x0000000000000000000000000000000000000000000000000000000000000000
  9 : 0x0000000000000000000000000000000000000000000000000000000000000000
  10: 0xE11605E324DDEC10186935F7D38FF4BCAB1F8812F9EE01851A60A5904E4A7A05
  11: 0x0000000000000000000000000000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000000000000000000000000000
  14: 0x306F9D8B94F17D93DC6E7CF8F5C79D652EB4C6C4D13DE2DDDC24AF416E13ECAF
  15: 0x0000000000000000000000000000000000000000000000000000000000000000
  16: 0x0000000000000000000000000000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000000000000000000000000000
sha384:
  0 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  1 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  2 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  3 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  4 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  5 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  6 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  7 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  8 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  9 : 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  10: 0x17AA683E1187D7821595F343403F157F34AA9635678D75FC8E6D3CA7D7A17E3626FC02A4B74A43F9B26D306928A88530
  11: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  12: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  13: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  14: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  15: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  16: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
sha512:
  0 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  1 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  2 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  3 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  4 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  5 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  6 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  7 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  8 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  9 : 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  10: 0x0FC0DF407F68CF00E7DE8380FA078CEAED2BF5970DC2D07BB049DA1DA49F31093C86C6059D6E6E9FF8389FB57724FDF037D4C90D2D3E4C2038DCBD9744B7B04C
  11: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  12: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  13: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  14: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  15: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  16: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

</code></pre>

**Comment by whooo** [comment] 2024-04-25 16:08
Duplicate of https://github.com/tpm2-software/tpm2-pytss/issues/570
Try with https://github.com/tpm2-software/tpm2-pytss/pull/571

**Closed by whooo** 2024-04-25 16:08 UTC
